# -*- coding: utf-8 -*-
"""Covid_19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzwi65cfImt0tfYOL0rRrdsGDzT2SZTv

**Covid-19 Analysis**  🦠

***Step 1 --> upload , read , and understand Data***
"""

from google.colab import files
Covid_data= files.upload()

import pandas as pd

covid_df =pd.read_csv("/content/country_wise_latest.csv")

covid_df.head()

covid_df.info()

covid_df.shape

"""***Step 2 --> Data Quality Checking***"""

covid_df.isnull().sum()

covid_df.isnull().sum() / len(covid_df) *100

covid_df.duplicated().sum()

"""No duplicate rows were found in the dataset

"""

covid_df["Country/Region"].unique()

covid_df.describe()

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=covid_df["Confirmed"])
plt.title("Boxplot for Confirmed Cases")
plt.show()

(covid_df["Confirmed"] < 0).sum()

"""# Data Quality Summary

The dataset was checked for data quality issues.

- No missing values were found.
- No duplicate rows were detected.
- All data types are appropriate.
- No negative values were found.
- Some high values were observed in confirmed cases, which are valid.

***Step 3 --> Data Cleaning / Wrangling***
"""

covid_df.columns

covid_df.columns = covid_df.columns.str.strip()
covid_df.columns = covid_df.columns.str.replace(" ", "_")
covid_df.columns = covid_df.columns.str.replace("/", "_")
covid_df.columns = covid_df.columns.str.replace("%", "percent")

covid_df.columns

"""# Clean column names

Column names were cleaned by removing spaces and special characters
to make them easier to use in analysis.
"""

covid_df.dtypes

covid_df["Death_Rate"] = (covid_df["Deaths"] / covid_df["Confirmed"]) * 100

covid_df["Recovery_Rate"] = (covid_df["Recovered"] / covid_df["Confirmed"]) * 100

covid_df.head()

"""**Feature Engineering**

New features were created to support analysis:

- Death_Rate: percentage of deaths relative to confirmed cases
- Recovery_Rate: percentage of recovered cases relative to confirmed cases
"""

covid_df = covid_df.sort_values(by="Confirmed", ascending=False)

covid_df.head()

"""***Step 4 --> EDA(Exploratory Data Analysis***)

"""

import matplotlib.pyplot as plt

top10 = covid_df.head(10)

plt.figure(figsize=(10,5))
plt.bar(top10["Country_Region"], top10["Confirmed"])
plt.title("Top 10 Countries by Confirmed Cases")
plt.xlabel("Country")
plt.ylabel("Confirmed Cases")
plt.xticks(rotation=90)
plt.show()

top10_deaths = covid_df.sort_values(by="Deaths", ascending=False).head(10)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.bar(top10_deaths["Country_Region"], top10_deaths["Deaths"])
plt.title("Top 10 Countries by Deaths")
plt.xlabel("Country")
plt.ylabel("Deaths")
plt.xticks(rotation=90)
plt.show()

top10_recovered = covid_df.sort_values(by = "Recovered" , ascending=False).head(10)
plt.figure(figsize=(10 , 5))
plt.bar(top10_recovered['Country_Region'] , top10_recovered['Recovered'])
plt.title("Top 10 Countries by Recovered Cases")
plt.xlabel("Country")
plt.ylabel("Recovered")
plt.show()

region_cases = covid_df.groupby("WHO_Region")["Confirmed"].sum().sort_values(ascending=False)

plt.figure(figsize=(8,5))
plt.bar(region_cases.index, region_cases.values)
plt.title("Total Confirmed Cases by WHO Region")
plt.xlabel("WHO Region")
plt.ylabel("Confirmed Cases")
plt.xticks(rotation=45)
plt.show()

covid_df[["Confirmed", "Deaths", "Recovered", "Active"]].corr()

plt.figure(figsize=(6,4))
sns.heatmap(covid_df[["Confirmed", "Deaths", "Recovered", "Active"]].corr(),
            annot=True, cmap="coolwarm")
plt.title("Correlation Between COVID Variables")
plt.show()

"""***Step 5 — Business Thinking***

# Business Insights

1. Countries with high confirmed cases also tend to have higher deaths.
2. Recovery rates vary significantly between countries, indicating differences in healthcare systems.
3. Some WHO regions are more affected than others, showing uneven global spread of COVID-19.
4. There is a strong positive correlation between confirmed cases and deaths.

# Recommendations

1. Countries with high infection rates should strengthen healthcare capacity.
2. Early detection and prevention strategies can reduce death rates.
3. Focus should be placed on regions with high growth rates of cases.
4. Data monitoring systems should be improved for faster response.
"""